# Generated by Django 6.1 on 2026-08-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('national', 'National'), ('international', 'International'), ('tamil_nadu', 'Tamil Nadu'), ('economy', 'Economy'), ('schemes', 'Government Schemes'), ('science_tech', 'Science & Technology'), ('environment', 'Environment'), ('awards', 'Awards'), ('appointments', 'Appointments'), ('sports', 'Sports')], max_length=30)),
                ('excerpt', models.CharField(blank=True, max_length=500)),
                ('content', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
