# Generated by Django 6.0.3 on 2026-09-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('current_affairs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ai_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='exam_relevance',
            field=models.CharField(blank=True, help_text='Comma-separated: UPSC, TNPSC, SSC, Banking, Railways, Defence', max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='source_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='article',
            name='source_url',
            field=models.URLField(blank=True, max_length=600, null=True, unique=True),
        ),
    ]
