# Generated by Django 6.0.3 on 2026-09-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('current_affairs', '0002_article_ai_summary_article_exam_relevance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_url',
            field=models.URLField(blank=True, max_length=800, null=True),
        ),
    ]
