# Generated by Django 6.1 on 2026-08-30 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remind_14_days', models.BooleanField(default=True)),
                ('remind_7_days', models.BooleanField(default=True)),
                ('remind_3_days', models.BooleanField(default=True)),
                ('remind_1_day', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrackedExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_applied', 'Not Applied'), ('planning', 'Planning to Apply'), ('applied', 'Applied'), ('admit_card_awaited', 'Admit Card Awaited'), ('exam_completed', 'Exam Completed'), ('result_awaited', 'Result Awaited'), ('qualified', 'Qualified'), ('not_qualified', 'Not Qualified')], default='not_applied', max_length=30)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_by', to='exams.exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_exams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'exam')},
            },
        ),
    ]
