# Generated by Django 6.1 on 2026-08-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('conducting_authority', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('notification_released', 'Notification Released'), ('application_open', 'Application Open'), ('application_closed', 'Application Closed'), ('exam_scheduled', 'Exam Scheduled'), ('result_released', 'Result Released')], default='upcoming', max_length=30)),
                ('qualification_required', models.CharField(max_length=255)),
                ('age_limit_min', models.IntegerField(blank=True, null=True)),
                ('age_limit_max', models.IntegerField(blank=True, null=True)),
                ('application_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('vacancy_count', models.IntegerField(blank=True, null=True)),
                ('application_start_date', models.DateField(blank=True, null=True)),
                ('application_end_date', models.DateField(blank=True, null=True)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('official_notification_url', models.URLField(blank=True)),
                ('last_verified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
