# Generated by Django 6.0.3 on 2026-09-02 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mock_tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testattempt',
            options={'ordering': ['-started_at']},
        ),
    ]
