# Generated by Django 6.1 on 2026-08-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('upsc', 'UPSC'), ('tnpsc_group1', 'TNPSC Group 1'), ('tnpsc_group2', 'TNPSC Group 2'), ('tnpsc_group3', 'TNPSC Group 3'), ('tnpsc_group4', 'TNPSC Group 4'), ('railways', 'Railways (RRB)'), ('ssc', 'SSC'), ('banking', 'Banking'), ('defence', 'Defence'), ('teaching', 'Teaching'), ('psus', 'PSUs & Others')], max_length=30)),
                ('material_type', models.CharField(choices=[('notes', 'Notes'), ('pdf', 'PDF'), ('video', 'Video'), ('flashcards', 'Flashcards'), ('current_affairs', 'Current Affairs')], max_length=30)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='materials/')),
                ('size_or_duration', models.CharField(blank=True, help_text='e.g. 24 pages, 32 min, 40 cards', max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
