# Generated by Django 6.0.3 on 2026-09-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show as featured/highlighted material'),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='is_locked',
            field=models.BooleanField(default=True, help_text='If True, login required to access'),
        ),
    ]
