# Generated by Django 6.0.3 on 2026-09-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_studymaterial_description_studymaterial_is_featured_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studymaterial',
            name='is_locked',
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='access_level',
            field=models.CharField(choices=[('free', 'Free — no login required'), ('premium', 'Premium — login + active subscription required')], default='premium', help_text="'free' = visible and downloadable by anyone, no login needed. 'premium' = requires login AND an active Premium subscription. Previous Year Question Papers are always forced to 'free' automatically.", max_length=10),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='material_type',
            field=models.CharField(choices=[('notes', 'Notes'), ('pdf', 'PDF'), ('video', 'Video'), ('flashcards', 'Flashcards'), ('current_affairs', 'Current Affairs'), ('previous_year', 'Previous Year Question Papers')], max_length=30),
        ),
    ]
