# Generated by Django 6.0.3 on 2026-09-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('otp_code', models.CharField(max_length=6)),
                ('otp_created_at', models.DateTimeField(auto_now=True)),
                ('attempts', models.IntegerField(default=0)),
            ],
        ),
    ]
